### ISSUE TITLE
Unused strings in source files

### ISSUE THREAD

**Issue by ghost** [5zig/The-5zig-Mod-Docs#20]
Hey mate! I've been taking a look at the en_US_ file from `lang` and `44`, and then I noticed the following unused strings, mostly related to old MCPVP servers.

Source strings from _The-5zig-Mod-Docs/resources/lang/44/language_en_US.properties_.

```
menu.mcpvp = MCPVP
mcpvp_servers.title = Select a MCPvP Server
mcpvp_servers.join_server = Join Server
mcpvp_servers.refresh = Refresh
raid.title = Raid Calculator
raid.tracked = Tracked %s blocks from %s to %s (%s in nether) in %s direction
raid.north = north
raid.south = south
raid.east = east
raid.west = west
raid.tracker_coords = Tracker Coords
raid.tracked_blocks = Tracked Blocks
raid.narrow = Narrow
raid.track = Track %s
```

Source strings from _The-5zig-Mod-Docs/resources/assets/the5zigmod/lang/en_us.lang_.

`the5zigmod.key.raid_calculator=MCPVP Raid Calculator`

That's pretty much of it. Since they are no longer used, may I remove them from source files?

**Comment by 5zig** [comment]
Hi, most of these strings are actually still used in the raid calculator gui. I'm a little nostalgic, so I still like to keep that feature inside the mod. :)
