### ISSUE TITLE
Incompability with Kami

### ISSUE THREAD

**Issue by 5HT2** [5zig/The-5zig-Mod-Docs#32]
So after a long troubleshooting session I found out 5zig causes MC 1.12.2 to crash with Kami `KAMI-master-b9-release` and 5zig `The 5zig Mod v3.12.5 for Minecraft 1.12.2`. Crash logs: 

~~edited out due to privacy concerns~~

They show what mods I was using when it crashed.

Please reply if I forgot any information.

Edit: The reason it's closed in Kami's repo is because 5zig has not even replied to this issue, and as it's not open source we can't fix it.
[Issue in Kami's repo](https://github.com/zeroeightysix/KAMI/issues/31)

**Comment by ZeroMemes** [comment]
This issue belongs [here](https://github.com/5zig/The-5zig-API). This is a repository for the documentation for 5zig, not 5zig (or rather, the api) itself.

**Comment by 5zig** [comment]
\*working on it*
It is definitely an issue of the 5zig mod, I should be able to fix it in the next update.

**Comment by 5HT2** [comment]
Closing as this is now fixed in 5zig reborn.
